[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\b/home/tc)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc2\0\0\0.\0\0\x5\x9b\0\0\x2.\0\0\x3\xc2\0\0\0.\0\0\x5\x9b\0\0\x2.\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc2\0\0\0.\0\0\x5\x9b\0\0\x2.)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(474 439)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/tc/Downloads/file_example_AVI_480_750kB.avi, file:///home/tc/Downloads/file_example_MP4_480_1_5MG.mp4, file:///home/tc/Downloads/file_example_MOV_480_700kB.mov
times=0, 0, 0
