[mgr]
prepend_keymap = [
  { on = "<Enter>", run = "plugin smart-enter", desc = "Enter folder or open file" },
  { on = "o", run = [ "enter", "quit" ], desc = "Enter folder and return terminal here" },
]
